#===  https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose

version: '3'
services:
 #==== NGINX ===================================================================#
 nginx:
    container_name: nginx
    build: requirements/nginx
    
    image: nginx
    ports:
      #- "81:81"
      - "443:443"
    volumes:
      - "www:/var/www/html"
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    env_file: .env
#==== MARIADB =================================================================#
 mariadb:
    build: requirements/mariadb/
    container_name: mariadb

    image: mariadb
    # ports:
    #   - "3306:3306"
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - inception
    restart: always
    env_file: .env

 #==== WORDPRESS ===============================================================#
 wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    
    image: wordpress
    # ports:
    #   - "9000:9000"
    volumes:
      - "www:/var/www/html"
    depends_on:
      - mariadb
      
    networks:
      - inception
    restart: always
    env_file: .env

#==============================================================================#
volumes:
  www:
    driver_opts:
      type: none
      device: /home/saray/data/www
      o: bind
  db:
    driver_opts:
      type: none
      device: /home/saray/data/mariadb
      o: bind
 
#============================================================================#
networks:
  inception:

# inception:
#    name: inception
#    driver: bridge
 