#===  https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose

version: '3'
services:
 #==== NGINX ===================================================================#
 nginx:
    container_name: nginx
    build: requirements/nginx
    
    image: nginx
    ports:
      - "81:81"
      - "443:443"
    volumes:
      - www:/var/www/html
    depends_on:
      - wordpress #mariadb
    networks:
      - inception
    restart: always
    env_file: .env

 #==== WORDPRESS ===============================================================#
 wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    
    image: wordpress
    ports:
      - "9000:9000"
    volumes:
      - "~/Desktop/inception/www:/var/www/html"
    depends_on:
      - mariadb
      
    networks:
      - inception
    restart: always
    env_file: .env
    #environment:
     # MYSQL_HOST:       ${MYSQL_HOST}
      #WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      #WP_DATABASE_USR:  ${WP_DATABASE_USR}
      #WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      #DOMAIN_NAME:      ${DOMAIN_NAME}
      #WP_TITLE:         ${WP_TITLE}
      #WP_ADMIN_USR:     ${WP_ADMIN_USR}
      #WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      #WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      #WP_USR:           ${WP_USR}
      #WP_PWD:           ${WP_PWD}
      #WP_EMAIL:         ${WP_EMAIL}
      #REDIS_HOST:       ${REDIS_HOST}
      #REDIS_PWD:        ${REDIS_PWD}


 #==== MARIADB =================================================================#
 mariadb:
    build: requirements/mariadb/
    container_name: mariadb

    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file: .env

    #environment:
     # MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      #WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      #WP_DATABASE_USR:  ${WP_DATABASE_USR}
      #WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
#==============================================================================#
volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_WWW_PATH}
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DB_PATH}
      o: bind
 
#============================================================================#
#networks:
 # inception:

 inception:
    name: inception
    driver: bridge
 