version: '3'
services:
 #==== mariadb ===================================================================#
 mariadb:
  container_name: mariadb
  image: mariadb:inception
  build:
    context: requirements/mariadb/
    args:
    - DB_CLIENT=wordpress.inception_network
    - MYSQL_DATABASE=wp_inception
    - MYSQL_USER=saray
    - MYSQL_USER2=saray2
    - DB_PASSWORD=123
    - MYSQL_PASSWORD=123
    - MYSQL_ROOT_PASSWORD=123s
  networks:
   - network
  env_file: .env
 #==== wordpress ==================================================================#
 wordpress:
  container_name: wordpress
  image: wordpress:inception
  build:
   context: requirements/wordpress/
   args:
    - WORDPRESS_DB_NAME=wp_inception
    - WORDPRESS_DB_USER=saray #${MYSQL_USER}
    - WORDPRESS_DB_PASSWORD=123 #${MYSQL_PASSWORD}
    - WORDPRESS_DB_HOST=mariadb:3306 #${DB_HOST}
    - DOMAIN_NAME=saray.42.fr
  networks:
   - network
  restart: always
  depends_on:
   - mariadb
  environment:
   - DOMAIN_NAME=saray.42.fr
   - TITLE=inception
   - WP_ADMIN_USER=saray
   - WP_ADMIN_PASSWORD=123
   - WP_ADMIN_MAIL=saray@student.42.fr
   - WP_USER=saray
   - WP_PASSWORD=123
  volumes:
      - website:/var/www/html
  env_file: .env
 #==== nginx ======================================================================#
 nginx:
  container_name: nginx
  image: nginx:inception
  build: requirements/nginx/
  ports:
   - "443:443"
  volumes:
   - website:/var/www/html
  depends_on:
   - wordpress
  networks:
   - network
  restart: always
  env_file: .env
#==================================================================================#
volumes:
 website:
  driver_opts:
   type: none
   device: /home/user42/data/website
   o: bind

 database:
  driver_opts:
   type: none
   device: /home/user42/data/database
   o: bind
  

#==================================================================================#
networks:
 network:


##############nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn

#===  https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose  

 